-- עדכון מסד הנתונים עם שדות Google OAuth
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS googleId VARCHAR(255) UNIQUE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS profilePicture VARCHAR(500);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS authProvider VARCHAR(20) DEFAULT 'local';
ALTER TABLE "User" ALTER COLUMN password DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN userName DROP NOT NULL;
